// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piniscsenbrruquxjtim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpbmlzY3NlbmJycnVxdXhqdGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTg1NzQsImV4cCI6MjA2OTk5NDU3NH0.MjuHWDMhdO85hXNyqH5jKClqr7uUxQvJq1r-y1vFN6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});